### ISSUE TITLE
environmental variable bug in session.py for inpadoc

### ISSUE THREAD

**Issue by samkorte** [parkerhancock/patent_client#35] opened 2020-04-08 01:43 UTC
I think the following if statement means that the environmental variables are never read so the code always reverts to reading ApiKey/Secret from the file system.  Looks like it should be os.environ.get("EPO_KEY", True):

CLIENT_SETTINGS = SETTINGS["EpoOpenPatentServices"]
if os.environ.get("EPO_KEY", False):  
    KEY = os.environ["EPO_KEY"]
    SECRET = os.environ["EPO_SECRET"]
else:
    KEY = CLIENT_SETTINGS["ApiKey"]
    SECRET = CLIENT_SETTINGS["Secret"]

**Comment by parkerhancock** [comment] 2020-04-13 15:18
Thanks for the bug report! But, I think the code provides the intended behavior. I'm using Python's [truthiness rules](https://docs.python.org/3/library/stdtypes.html#truth-value-testing) to create a conditional that returns False if the environment variable is either not set, or is falsy (e.g. `""`, `None`, `False`, or similar) using the `dict.get(key, default)` accessor.

````python
# os.environ is a dictionary. 
if os.environ.get("EPO_KEY", False):
    # This gets evaluated if "EPO_KEY" env var is set, setting KEY and SECRET to the env variables
    KEY = os.environ["EPO_KEY"]
    SECRET = os.environ["EPO_SECRET"]
else:
    # This gets evaluated if "EPO_KEY" env var is NOT set, using the library's default settings.
    KEY = CLIENT_SETTINGS["ApiKey"]
    SECRET = CLIENT_SETTINGS["Secret"]
````

Let me know if that still isn't clear, or if I've messed something up more severely than I thought!

Long-term, I'm working towards moving towards a more Django-like configuration, where all configuration variables are in a single config.py file, and any can be overridden by environment variables prefixed with "PATENT_CLIENT." So this would be "PATENT_CLIENT_EPO_SECRET." But I'll be sure to document that change before I make it :)

Thanks!

**Closed by parkerhancock** 2020-04-13 15:18 UTC
