### ISSUE TITLE
Unable to use Patent Client package

### ISSUE THREAD

**Issue by prana2023** [parkerhancock/patent_client#153] opened 2024-05-01 16:07 UTC
I installed Patent Client 5.0.0 and Python 3.9 version. I am running the following code:

from patent_client import USApplication

google_apps = USApplication.objects.filter(first_named_applicant='Google LLC')

print(len(google_apps) > 1000)

It errors out with the following error:

" import nest_asyncio
ModuleNotFoundError: No module named 'nest_asyncio'"

I installed the nest_asyncio package and re-run and I got below error stack: I am unable to make any progress in resolving this error:

  **File "/Users/ub33/PycharmProjects/tpp/constants.py", line 1, in <module>
    from patent_client import USApplication
  File "/Users/ub33/PycharmProjects/tpp/venv/lib/python3.9/site-packages/patent_client/__init__.py", line 53, in <module>
    from ._sync import *
  File "/Users/ub33/PycharmProjects/tpp/venv/lib/python3.9/site-packages/patent_client/_sync/__init__.py", line 7, in <module>
    from .epo.ops.published.model import Inpadoc
  File "/Users/ub33/PycharmProjects/tpp/venv/lib/python3.9/site-packages/patent_client/_sync/epo/ops/__init__.py", line 7, in <module>
    from .family.model import Family
  File "/Users/ub33/PycharmProjects/tpp/venv/lib/python3.9/site-packages/patent_client/_sync/epo/ops/family/model.py", line 11, in <module>
    from ..number_service.model import DocumentId
  File "/Users/ub33/PycharmProjects/tpp/venv/lib/python3.9/site-packages/patent_client/_sync/epo/ops/number_service/model.py", line 11, in <module>
    from patent_client.util.pydantic_util import Date
  File "/Users/ub33/PycharmProjects/tpp/venv/lib/python3.9/site-packages/patent_client/util/pydantic_util.py", line 16, in <module>
    def parse_datetime(date_obj: str | datetime.datetime) -> datetime.datetime:
TypeError: unsupported operand type(s) for |: 'type' and 'type'**

**Comment by parkerhancock** [comment] 2024-05-01 17:54
Thanks for flagging this! Let me re-run the test suite on 3.9. This is caused by an issue in how 3.10 and later allow for more flexible type annotations. 

Still surprised you see this issue at runtime, but whatever. I'll see if I can fix it.

Thanks!

**Comment by parkerhancock** [comment] 2024-05-02 16:59
Resolved in v5.0.1! Try 

```bash
pip install --upgrade patent_client
```

Let me know if you're still having issues!

**Closed by parkerhancock** 2024-05-02 16:59 UTC

**Comment by prana2023** [comment] 2024-05-02 17:16
The issue is resolved now. Thanks for quick turn around.

**Comment by deg** [comment] 2024-05-08 11:52
I had this same problem today with v5.0.11 (using Python 3.12.1 and pipenv).
I worked around it with an explicit `$ pipenv install nest_asyncio`

**Comment by parkerhancock** [comment] 2024-05-08 15:48
I've fixed this issue in v5.0.13 and removed the now vestigial call to nest_asyncio, so this shouldn't be a problem anymore.
